### ISSUE TITLE
 add_weight() got multiple values for argument 'name'

### ISSUE THREAD

**Issue by zhangby2085** [madrugado/Attention-Based-Aspect-Extraction#2]
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    model = create_model(args, overall_maxlen, vocab)
  File "/home/boyang/aspect extraction/Attention-Based-Aspect-Extraction-master/code/model.py", line 45, in create_model
    b_constraint=MaxNorm(10))([e_w, y_s])
  File "/home/boyang/anaconda2/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/home/boyang/anaconda2/lib/python3.7/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/boyang/aspect extraction/Attention-Based-Aspect-Extraction-master/code/my_layers.py", line 42, in build
    constraint=self.W_constraint)
TypeError: add_weight() got multiple values for argument 'name'

May I ask what type of error is this :)

**Comment by madrugado** [comment]
Hello, I have seen this error, it's related to the new Keras versions. I'll get it fixed in a few days.

**Comment by madrugado** [comment]
@zhangby2085 please check if there are still issues

**Comment by zhangby2085** [comment]
A very big thank you for the information, have a nice day :) 
Checking...

**Comment by zhangby2085** [comment]
python train.py --emb-name ../preprocessed_data/$domain/w2v_embedding --domain restaurant -o output_dir
Above command works well, when I give domain in beer:
code$ python train.py --emb-name ../preprocessed_data/$domain/w2v_embedding 

> --domain beer

 -o output_dir
Using TensorFlow backend.
2019-10-15 11:51:46,768 INFO Arguments:
2019-10-15 11:51:46,769 INFO   algorithm: adam
2019-10-15 11:51:46,769 INFO   aspect_size: 14
2019-10-15 11:51:46,769 INFO   batch_size: 32
2019-10-15 11:51:46,769 INFO   command: train.py --emb-name ../preprocessed_data//w2v_embedding --domain beer -o output_dir
2019-10-15 11:51:46,769 INFO   domain: beer
2019-10-15 11:51:46,769 INFO   emb_dim: 100
2019-10-15 11:51:46,769 INFO   emb_name: ../preprocessed_data//w2v_embedding
2019-10-15 11:51:46,769 INFO   epochs: 15
2019-10-15 11:51:46,769 INFO   maxlen: 256
2019-10-15 11:51:46,770 INFO   neg_size: 20
2019-10-15 11:51:46,770 INFO   ortho_reg: 0.1
2019-10-15 11:51:46,770 INFO   out_dir_path: output_dir
2019-10-15 11:51:46,770 INFO   seed: 1234
2019-10-15 11:51:46,770 INFO   vocab_size: 9000
Reading data from beer
 Creating vocab ...
   108059079 total words, 17156 unique words
  keep the top 9000 words
 Reading dataset ...
  train set
   <num> hit rate: 0.61%, <unk> hit rate: 1.35%
  test set
   <num> hit rate: 0.55%, <unk> hit rate: 1.31%
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    train_x = sequence.pad_sequences(train_x, maxlen=overall_maxlen)
  File "/home/boyang/anaconda2/lib/python3.7/site-packages/keras_preprocessing/sequence.py", line 83, in pad_sequences
    x = np.full((num_samples, maxlen) + sample_shape, value, dtype=dtype)
  File "/home/boyang/anaconda2/lib/python3.7/site-packages/numpy/core/numeric.py", line 332, in full
    a = empty(shape, dtype, order)
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (16857450, 256) and data type int32

Please take a look :)

**Comment by madrugado** [comment]
the stacktrace said that you're trying to load too big dataset, try smaller one please
